/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SkillsLazyImport = createFileRoute('/skills')()
const ProjectsLazyImport = createFileRoute('/projects')()
const ExperienceLazyImport = createFileRoute('/experience')()
const CertificatesLazyImport = createFileRoute('/certificates')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SkillsLazyRoute = SkillsLazyImport.update({
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/skills.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const ExperienceLazyRoute = ExperienceLazyImport.update({
  path: '/experience',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/experience.lazy').then((d) => d.Route))

const CertificatesLazyRoute = CertificatesLazyImport.update({
  path: '/certificates',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/certificates.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/certificates': {
      preLoaderRoute: typeof CertificatesLazyImport
      parentRoute: typeof rootRoute
    }
    '/experience': {
      preLoaderRoute: typeof ExperienceLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      preLoaderRoute: typeof SkillsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CertificatesLazyRoute,
  ExperienceLazyRoute,
  ProjectsLazyRoute,
  SkillsLazyRoute,
])

/* prettier-ignore-end */
